"""feat: init commit 

Revision ID: 60e8985e4cea
Revises: 
Create Date: 2023-10-12 05:30:11.466766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60e8985e4cea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('banks_req',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bik', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('kor_score', sa.String(length=20), nullable=False),
    sa.Column('swift', sa.String(length=11), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks_req')
    op.drop_table('users')
    # ### end Alembic commands ###
