"""empty message

Revision ID: a4aa9c96a9fd
Revises: c782dc335092
Create Date: 2023-10-11 12:38:58.561685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4aa9c96a9fd'
down_revision = 'c782dc335092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
