version: "3.8"

services:
   postgres:
    image: postgres:latest
    container_name:  myDB
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root2
      POSTGRES_PASSWORD: root3
    ports:
      - "5432:5432"
   api:
    build: .
    command: python app/router.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
